# Generated by Django 3.1.4 on 2020-12-14 07:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressType',
            fields=[
                ('address_type', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('address_name', models.CharField(blank=True, max_length=80, null=True)),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.client')),
            ],
            options={
                'ordering': ['client_id', 'address_type'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.BigAutoField(auto_created=True, default=1, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, max_length=15, null=True)),
                ('title', models.CharField(blank=True, choices=[('MR', 'Mr.'), ('MS', 'Ms.'), ('MRS', 'Mrs.'), ('DR', 'Dr.')], default='MR', max_length=3, verbose_name='title')),
                ('first_name', models.CharField(max_length=80)),
                ('middle_name', models.CharField(default='', max_length=80)),
                ('last_name', models.CharField(default='', max_length=80)),
                ('name_at_birth', models.CharField(default='', max_length=80)),
                ('full_name', models.CharField(default='', max_length=160)),
                ('nick_name', models.CharField(default='', max_length=80)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Third Gender'), ('U', 'Unknown')], default='M', max_length=1)),
                ('birth_place', models.CharField(blank=True, default='', max_length=80)),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed'), ('I', 'In a Relationship'), ('P', 'Separated')], default='M', max_length=1)),
                ('occupation', models.CharField(default='', max_length=80)),
                ('nationality', models.CharField(default='', max_length=80)),
                ('date_of_birth', models.DateField()),
                ('date_of_marriage', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('valid_from', models.DateField(default=datetime.date.today)),
                ('valid_to', models.DateField(default='31/12/9999')),
                ('id_number', models.CharField(max_length=80)),
                ('perm_house', models.CharField(blank=True, help_text='House Number', max_length=20, null=True)),
                ('perm_building', models.CharField(blank=True, help_text='Building Name', max_length=80, null=True)),
                ('perm_street_1', models.CharField(blank=True, help_text='Street 1', max_length=80, null=True)),
                ('perm_street_2', models.CharField(blank=True, help_text='Street 2', max_length=80, null=True)),
                ('perm_village', models.CharField(blank=True, help_text='Village', max_length=80, null=True)),
                ('perm_taluk', models.CharField(blank=True, help_text='Taluk', max_length=80, null=True)),
                ('perm_district', models.CharField(blank=True, help_text='District', max_length=80, null=True)),
                ('perm_city', models.CharField(max_length=40)),
                ('perm_postal_code', models.CharField(max_length=20)),
                ('perm_region', models.CharField(blank=True, help_text='Region/State', max_length=40, null=True)),
                ('perm_country', models.CharField(blank=True, max_length=40, null=True)),
                ('cont_house', models.CharField(blank=True, help_text='House Number', max_length=20, null=True)),
                ('cont_building', models.CharField(blank=True, help_text='Building Name', max_length=80, null=True)),
                ('cont_street_1', models.CharField(blank=True, help_text='Street 1', max_length=80, null=True)),
                ('cont_street_2', models.CharField(blank=True, help_text='Street 2', max_length=80, null=True)),
                ('cont_village', models.CharField(blank=True, help_text='Village', max_length=80, null=True)),
                ('cont_taluk', models.CharField(blank=True, help_text='Taluk', max_length=80, null=True)),
                ('cont_district', models.CharField(blank=True, help_text='District', max_length=80, null=True)),
                ('cont_city', models.CharField(blank=True, max_length=40, null=True)),
                ('cont_postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('cont_region', models.CharField(blank=True, help_text='Region/State', max_length=40, null=True)),
                ('cont_country', models.CharField(blank=True, max_length=40, null=True)),
                ('telephone', models.CharField(max_length=15)),
                ('mobile_phone', models.CharField(max_length=15)),
                ('alternate_contact', models.CharField(max_length=15)),
                ('email_id', models.CharField(blank=True, max_length=80, null=True)),
                ('rel_title', models.CharField(blank=True, choices=[('MR', 'Mr.'), ('MS', 'Ms.'), ('MRS', 'Mrs.'), ('DR', 'Dr.')], default='MR', max_length=3, verbose_name='title')),
                ('rel_first_name', models.CharField(max_length=80)),
                ('rel_middle_name', models.CharField(blank=True, max_length=80, null=True)),
                ('rel_last_name', models.CharField(blank=True, max_length=80, null=True)),
                ('rel_full_name', models.CharField(blank=True, max_length=160, null=True)),
                ('status', models.CharField(blank=True, choices=[('A', 'Active'), ('I', 'Inactive'), ('D', 'Deleted')], default='A', max_length=1)),
                ('created_on', models.DateTimeField(auto_now=True, verbose_name='Created On')),
                ('created_by', models.CharField(blank=True, default='', max_length=20)),
                ('changed_on', models.DateTimeField(auto_now_add=True, verbose_name='Changed On')),
                ('changed_by', models.CharField(blank=True, default='', max_length=20)),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.client')),
            ],
            options={
                'ordering': ['client_id', 'customer_id'],
            },
        ),
        migrations.CreateModel(
            name='RelationshipType',
            fields=[
                ('relationship_type', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('relationship_name', models.CharField(blank=True, max_length=80, null=True)),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.client')),
            ],
            options={
                'ordering': ['client_id', 'relationship_type'],
            },
        ),
        migrations.CreateModel(
            name='IdentificationType',
            fields=[
                ('id_type', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('id_name', models.CharField(blank=True, max_length=80, null=True)),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.client')),
            ],
            options={
                'ordering': ['client_id', 'id_type'],
            },
        ),
        migrations.CreateModel(
            name='CustomerIdentification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=80)),
                ('created_on', models.DateTimeField()),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('changed_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('changed_by', models.CharField(blank=True, max_length=20, null=True)),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.client')),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer')),
                ('id_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.identificationtype')),
            ],
            options={
                'ordering': ['client_id', 'customer_id', 'id_type'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='id_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.identificationtype'),
        ),
        migrations.AddField(
            model_name='customer',
            name='rel_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.relationshiptype'),
        ),
        migrations.CreateModel(
            name='CusomterAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(blank=True, help_text='House Number', max_length=20, null=True)),
                ('building', models.CharField(blank=True, help_text='Building Name', max_length=80, null=True)),
                ('street_1', models.CharField(blank=True, help_text='Street 1', max_length=80, null=True)),
                ('street_2', models.CharField(blank=True, help_text='Street 2', max_length=80, null=True)),
                ('street_3', models.CharField(blank=True, help_text='Village', max_length=80, null=True)),
                ('street_4', models.CharField(blank=True, help_text='Taluk', max_length=80, null=True)),
                ('street_5', models.CharField(blank=True, help_text='District', max_length=80, null=True)),
                ('city', models.CharField(max_length=40)),
                ('postal_code', models.CharField(max_length=20)),
                ('region', models.CharField(blank=True, help_text='Region/State', max_length=40, null=True)),
                ('country', models.CharField(blank=True, max_length=40, null=True)),
                ('telephone', models.CharField(max_length=15)),
                ('mobile_phone', models.CharField(max_length=15)),
                ('alternate_contact', models.CharField(max_length=15)),
                ('email_id', models.CharField(max_length=80)),
                ('created_on', models.DateTimeField()),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('changed_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('changed_by', models.CharField(blank=True, max_length=20, null=True)),
                ('address_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.addresstype')),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.client')),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer')),
            ],
            options={
                'ordering': ['client_id', 'customer_id'],
            },
        ),
    ]
