# Generated by Django 3.1.4 on 2020-12-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='rel_mobile',
            field=models.CharField(default=242434, max_length=15),
            preserve_default=False,
        ),
    ]
