# Generated by Django 3.1.4 on 2020-12-14 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_rel_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cusomteraddress',
            name='address_type',
        ),
        migrations.RemoveField(
            model_name='cusomteraddress',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='cusomteraddress',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='customeridentification',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='customeridentification',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='customeridentification',
            name='id_type',
        ),
        migrations.DeleteModel(
            name='AddressType',
        ),
        migrations.DeleteModel(
            name='CusomterAddress',
        ),
        migrations.DeleteModel(
            name='CustomerIdentification',
        ),
    ]
