# Generated by Django 3.1.4 on 2020-12-14 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_productcategory_company_code'),
        ('customer', '0003_auto_20201214_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('group_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=80)),
                ('created_on', models.DateTimeField(auto_now=True, verbose_name='Created On')),
                ('created_by', models.CharField(blank=True, default='', max_length=20)),
                ('changed_on', models.DateTimeField(auto_now_add=True, verbose_name='Changed On')),
                ('changed_by', models.CharField(blank=True, default='', max_length=20)),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.client')),
                ('customer_id', models.ManyToManyField(to='customer.Customer')),
            ],
            options={
                'ordering': ['client_id', 'group_id'],
            },
        ),
    ]
