# Generated by Django 3.1.4 on 2020-12-14 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customergroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customergroup',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
