# Generated by Django 3.1.4 on 2020-12-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20201218_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gua_first_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gua_mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
