# Generated by Django 3.1.4 on 2020-12-18 04:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_productcategory_company_code'),
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanmaster',
            old_name='first_emi',
            new_name='amount_first_instal',
        ),
        migrations.RenameField(
            model_name='loanmaster',
            old_name='status',
            new_name='loan_status',
        ),
        migrations.RemoveField(
            model_name='loanmaster',
            name='emi_end',
        ),
        migrations.RemoveField(
            model_name='loanmaster',
            name='emi_start',
        ),
        migrations.AddField(
            model_name='loanmaster',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.currency'),
        ),
        migrations.AddField(
            model_name='loanmaster',
            name='disbursal_status',
            field=models.CharField(blank=True, choices=[('N', 'Not Disbursed'), ('P', 'Partially Disbursed'), ('F', 'Fully Disbursed')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='loanmaster',
            name='due_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanmaster',
            name='instalment_end',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='loanmaster',
            name='instalment_start',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='loanmaster',
            name='application_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='loanmaster',
            name='disbursal_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='loanmaster',
            name='interest_start',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.CreateModel(
            name='LoanAsset',
            fields=[
                ('asset_no', models.CharField(auto_created=True, editable=False, max_length=15, primary_key=True, serialize=False)),
                ('asset_desc', models.CharField(blank=True, max_length=80, null=True)),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=40, null=True)),
                ('invoice_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('make', models.CharField(blank=True, max_length=80, null=True)),
                ('model', models.CharField(blank=True, max_length=80, null=True)),
                ('chasis_no', models.CharField(blank=True, max_length=80, null=True)),
                ('engine_no', models.CharField(blank=True, max_length=30, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('registration_no', models.CharField(blank=True, max_length=30, null=True)),
                ('rto', models.CharField(blank=True, max_length=30, null=True)),
                ('supplier', models.CharField(blank=True, max_length=80, null=True)),
                ('category', models.CharField(blank=True, max_length=30, null=True)),
                ('reposession_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('sales_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('imei1', models.CharField(blank=True, max_length=30, null=True)),
                ('imei2', models.CharField(blank=True, max_length=30, null=True)),
                ('invoice_remark', models.CharField(blank=True, max_length=80, null=True)),
                ('asset_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('blue_book_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('sales_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('rbi_code', models.CharField(blank=True, max_length=30, null=True)),
                ('deliver_order', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('do_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('first_inspect_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('regd_remark', models.CharField(blank=True, max_length=80, null=True)),
                ('rc_status', models.CharField(blank=True, max_length=20, null=True)),
                ('rcsu_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('created_on', models.DateTimeField(auto_now=True, verbose_name='Created On')),
                ('created_by', models.CharField(blank=True, default='', max_length=20)),
                ('changed_on', models.DateTimeField(auto_now_add=True, verbose_name='Changed On')),
                ('changed_by', models.CharField(blank=True, default='', max_length=20)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.client')),
                ('loan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loan.loanmaster')),
            ],
        ),
    ]
