# Generated by Django 3.1.4 on 2020-12-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_auto_20201218_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanmaster',
            name='service_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
    ]
