# Generated by Django 3.1.4 on 2020-12-19 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0006_auto_20201219_1908'),
        ('loan', '0007_auto_20201218_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanmaster',
            options={'ordering': ['client_id', 'loan_no']},
        ),
        migrations.AlterField(
            model_name='loanmaster',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.currency'),
        ),
    ]
