# Generated by Django 3.1.4 on 2020-12-19 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0008_auto_20201219_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanmaster',
            name='due_date',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
