# Generated by Django 3.1.4 on 2020-12-20 14:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0007_product_interest_rate'),
        ('loan', '0009_auto_20201219_2119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanasset',
            options={'ordering': ['client_id', 'loan', 'asset_no']},
        ),
        migrations.AlterField(
            model_name='loanmaster',
            name='loan_no',
            field=models.CharField(auto_created=True, editable=False, max_length=12, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='LoanTransactions',
            fields=[
                ('transaction_no', models.IntegerField(primary_key=True, serialize=False)),
                ('trasaction_type', models.CharField(blank=True, choices=[('I', 'Instalment Payment'), ('D', 'Disbursal'), ('F', 'First Payment'), ('C', 'CBC Charges'), ('L', 'LP Charges'), ('O', 'Overdue Charges'), ('P', 'Part Payment'), ('X', 'Fore Closure'), ('M', 'Other Payments')], default='I', max_length=1)),
                ('posting_date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField(default=datetime.date.today)),
                ('payment_mode', models.CharField(choices=[('B', 'Bank Account Transfer'), ('C', 'CHEQUE'), ('D', 'Digital Payment'), ('E', 'ECS'), ('N', 'NACH'), ('S', 'CASH')], default='N', max_length=1)),
                ('payment_no', models.CharField(blank=True, default='', max_length=20)),
                ('payment_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('debit_credit', models.CharField(choices=[('D', 'DR'), ('C', 'CR')], default='D', max_length=1)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('invoice_no', models.CharField(max_length=20)),
                ('invoice_reference', models.CharField(blank=True, max_length=40, null=True)),
                ('created_on', models.DateTimeField(auto_now=True, verbose_name='Created On')),
                ('created_by', models.CharField(blank=True, default='', max_length=20)),
                ('changed_on', models.DateTimeField(auto_now_add=True, verbose_name='Changed On')),
                ('changed_by', models.CharField(blank=True, default='', max_length=20)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.client')),
                ('loan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loan.loanmaster')),
            ],
            options={
                'ordering': ['client_id', 'loan', 'trasaction_type', 'transaction_no'],
            },
        ),
    ]
