# Generated by Django 3.1.4 on 2020-12-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0010_auto_20201220_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loantransactions',
            name='transaction_no',
            field=models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
