# Generated by Django 3.1.4 on 2020-12-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0011_auto_20201220_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loantransactions',
            options={'ordering': ['client_id', 'loan', 'transaction_no']},
        ),
        migrations.AddField(
            model_name='loantransactions',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='loantransactions',
            name='transaction_status',
            field=models.CharField(blank=True, choices=[('O', 'Open'), ('F', 'Fully Paid'), ('P', 'Partially Paid')], default='O', max_length=1),
        ),
    ]
