# Generated by Django 3.1.4 on 2020-12-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0013_auto_20201223_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loantransactions',
            name='invoice_no',
            field=models.CharField(auto_created=True, max_length=20),
        ),
    ]
