# Generated by Django 3.1.4 on 2020-12-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0017_auto_20201227_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantransactions',
            name='transaction_id',
            field=models.CharField(auto_created=True, default='sk', editable=False, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loantransactions',
            name='transaction_no',
            field=models.IntegerField(auto_created=True, editable=False),
        ),
    ]
