# Generated by Django 3.1.4 on 2021-01-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0019_auto_20210101_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loantransactions',
            name='trasaction_type',
            field=models.CharField(blank=True, choices=[('I', 'Instalment Payment'), ('D', 'Disbursal'), ('F', 'First Payment'), ('C', 'CBC Charges'), ('L', 'LP Charges'), ('O', 'Overdue Charges'), ('P', 'Part Payment'), ('X', 'Fore Closure'), ('M', 'Other Payments'), ('S', 'Service Charges'), ('G', 'GST Charges'), ('V', 'VAT Charges'), ('E', 'CESS Charges'), ('T', 'Other Charges')], default='I', max_length=1),
        ),
    ]
