# Generated by Django 3.1.4 on 2021-01-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0020_auto_20210103_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loantransactions',
            old_name='trasaction_type',
            new_name='transaction_type',
        ),
        migrations.AlterField(
            model_name='loantransactions',
            name='transaction_status',
            field=models.CharField(blank=True, choices=[('O', 'Not Paid'), ('F', 'Fully Paid'), ('P', 'Partially Paid')], default='O', max_length=1),
        ),
    ]
