# Generated by Django 3.1.4 on 2021-01-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0021_auto_20210103_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantransactions',
            name='cheque_bank',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='loantransactions',
            name='payment_no',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
