# Generated by Django 3.1.4 on 2021-01-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0022_auto_20210110_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loantransactions',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=15, null=True),
        ),
    ]
