# Generated by Django 3.1.4 on 2021-01-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0023_auto_20210124_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loantransactions',
            name='cheque_bank',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
