# Generated by Django 3.1.4 on 2020-12-14 07:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingYear',
            fields=[
                ('accounting_year', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('acc_year_name', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ['client_id', 'accounting_year'],
            },
        ),
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('coa_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('coa_name', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ['client_id', 'coa_id'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyCode',
            fields=[
                ('company_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=60)),
                ('gstin', models.CharField(blank=True, max_length=40, null=True)),
                ('unit_number', models.CharField(blank=True, max_length=20, null=True)),
                ('building', models.CharField(blank=True, max_length=80, null=True)),
                ('street_1', models.CharField(blank=True, max_length=80, null=True)),
                ('street_2', models.CharField(blank=True, max_length=80, null=True)),
                ('street_3', models.CharField(blank=True, max_length=80, null=True)),
                ('street_4', models.CharField(blank=True, max_length=80, null=True)),
                ('city', models.CharField(max_length=40)),
                ('postal_code', models.CharField(max_length=20)),
                ('region', models.CharField(blank=True, max_length=40, null=True)),
                ('country', models.CharField(blank=True, max_length=40, null=True)),
                ('accounting_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.accountingyear')),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.client')),
                ('coa_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.chartofaccounts')),
            ],
            options={
                'ordering': ['client_id', 'company_code'],
            },
        ),
        migrations.CreateModel(
            name='ControllingArea',
            fields=[
                ('controlling_area', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('ca_name', models.CharField(max_length=60)),
                ('accounting_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.accountingyear')),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.client')),
                ('coa_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.chartofaccounts')),
            ],
            options={
                'ordering': ['client_id', 'controlling_area'],
            },
        ),
        migrations.CreateModel(
            name='ProfitCentre',
            fields=[
                ('profit_centre', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('pc_name', models.CharField(max_length=60)),
                ('valid_from', models.DateField(default=datetime.date.today)),
                ('valid_to', models.DateField()),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.client')),
                ('controlling_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.controllingarea')),
            ],
            options={
                'ordering': ['client_id', 'profit_centre'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_key', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('currency_name', models.CharField(max_length=60)),
                ('decimal_places', models.IntegerField()),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.client')),
            ],
            options={
                'ordering': ['client_id', 'currency_key'],
            },
        ),
        migrations.CreateModel(
            name='CostCentre',
            fields=[
                ('cost_centre', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('cc_name', models.CharField(max_length=60)),
                ('valid_from', models.DateField(default=datetime.date.today)),
                ('valid_to', models.DateField()),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.client')),
                ('company_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.companycode')),
                ('controlling_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.controllingarea')),
                ('currency_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.currency')),
            ],
            options={
                'ordering': ['client_id', 'cost_centre'],
            },
        ),
        migrations.AddField(
            model_name='controllingarea',
            name='currency_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.currency'),
        ),
        migrations.AddField(
            model_name='companycode',
            name='controlling_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.controllingarea'),
        ),
        migrations.AddField(
            model_name='companycode',
            name='currency_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.currency'),
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.client'),
        ),
        migrations.CreateModel(
            name='BusinessArea',
            fields=[
                ('business_area', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('ba_name', models.CharField(max_length=60)),
                ('valid_from', models.DateField(default=datetime.date.today)),
                ('valid_to', models.DateField()),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.client')),
                ('company_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.companycode')),
                ('controlling_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.controllingarea')),
            ],
            options={
                'ordering': ['client_id', 'business_area'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=60)),
                ('valid_from', models.DateField(default=datetime.date.today)),
                ('valid_to', models.DateField()),
                ('business_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.businessarea')),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.client')),
                ('company_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.companycode')),
                ('controlling_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.controllingarea')),
            ],
            options={
                'ordering': ['client_id', 'branch'],
            },
        ),
        migrations.CreateModel(
            name='BankMaster',
            fields=[
                ('bank_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=60)),
                ('bank_branch', models.CharField(max_length=60)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('swift_code', models.CharField(blank=True, max_length=20, null=True)),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.client')),
            ],
            options={
                'ordering': ['client_id', 'bank_id'],
            },
        ),
        migrations.AddField(
            model_name='accountingyear',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.client'),
        ),
    ]
