# Generated by Django 3.1.4 on 2020-12-14 09:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('product_category', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=80)),
                ('valid_from', models.DateField(default=datetime.date.today)),
                ('valid_to', models.DateField()),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.client')),
            ],
            options={
                'ordering': ['client_id', 'product_category'],
            },
        ),
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('product_sub_category', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('sub_category_name', models.CharField(max_length=80)),
                ('valid_from', models.DateField(default=datetime.date.today)),
                ('valid_to', models.DateField()),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.client')),
                ('product_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.productcategory')),
            ],
            options={
                'ordering': ['client_id', 'product_sub_category'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=80)),
                ('valid_from', models.DateField(default=datetime.date.today)),
                ('valid_to', models.DateField()),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.client')),
                ('product_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.productcategory')),
                ('product_sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.productsubcategory')),
            ],
            options={
                'ordering': ['client_id', 'product_id'],
            },
        ),
    ]
