# Generated by Django 3.1.4 on 2020-12-14 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_product_productcategory_productsubcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='company_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.companycode'),
        ),
    ]
