# Generated by Django 3.1.4 on 2020-12-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_productcategory_company_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id_start',
            field=models.CharField(default='SLB', max_length=5),
            preserve_default=False,
        ),
    ]
