# Generated by Django 3.1.4 on 2020-12-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0004_product_product_id_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id_start',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
